### ISSUE TITLE
Error when trying to run tmesh command: tmesh: error while loading shared libraries: libtme.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by asmithrsa** [phabrics/nme#2]
I keep getting this error when trying to load tmesh. I am now running on the newest version of Lubuntu still on the release of tme on OSDN. I tried exporting the TME_MODULE_PATH as well as the LD_LIBRARY_PATH to point to the right location but it did not change anything. configure, make and make install ran with no errors.

**Comment by asmithrsa** [comment]
Doing ./configure with --disable-shared now lets me get past this error and the tmesh shell starts but the GUI using GTK does not open.

**Comment by phabrics** [comment]
Not sure why that happens. I've compiled and run for Ubuntu successfully. I think one issue that I've seen is that after installing the first time on some machines, an ldconfig needs to be run to update the shared library cache. Usually a restart works as well. There should be no need to build a static version.

As to the GUI not opening, be sure to start the machine up. If that's not the issue, you can try one of the other GUIs (vnc or sdl). I have seen the GUI not open for certain machine types in the past, but I thought it was working this last time. I know that sun4 works for sure. sun3 sometimes has issues opening with GTK4, but I thought it worked with GTK3. What version are you running?

**Comment by asmithrsa** [comment]
Thank you I will try a restart. As for GTK, I'm using GTK3. Is there a command to start the machine up after the tmesh command?

**Comment by asmithrsa** [comment]
Ohh I forgot that the original TME doesn't start up by itself like Ambi's repo

**Comment by asmithrsa** [comment]
When I do the tmesh --log -config_file tmesh comes up but when I try "ls" nothing shows up

**Comment by phabrics** [comment]
I have confirmed that the ldconfig was the issue with the shared libraries. You can simply run it after the install and it should work! No need to recompile static or restart or set any environment variables. Of course, you can also run it static if you wish.

**Comment by asmithrsa** [comment]
Ok I can confirm that something is going wrong when loading up a disk image backup of a real sun machine. The window seems to freeze while it is checking the file systems. When I started to do a fresh install of SunOS it didn't seem to freeze. I don't think it's my img file because it always booted up fine when I used tme-0.8 on Ambi's repo.

**Comment by phabrics** [comment]
Thanks for closing this. It should be documented somewhere. I'm also thinking of putting it into the install step of the build to avoid it being a future issue. I might do that.
